global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'llm-demo-api'
    static_configs:
      - targets: ['model-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s