apiVersion: v1
kind: Namespace
metadata:
  name: llm-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-demo-api
  namespace: llm-demo
  labels:
    app: llm-demo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: llm-demo-api
  template:
    metadata:
      labels:
        app: llm-demo-api
    spec:
      containers:
      - name: llm-demo-api
        image: llm-demo-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: MAX_WORKERS
          value: "4"
        - name: TIMEOUT
          value: "300"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
            nvidia.com/gpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: log-storage
          mountPath: /app/logs
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc
      - name: log-storage
        emptyDir: {}
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: llm-demo-api-service
  namespace: llm-demo
spec:
  selector:
    app: llm-demo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-demo-api-hpa
  namespace: llm-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-demo-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-demo-config
  namespace: llm-demo
data:
  MAX_WORKERS: "4"
  TIMEOUT: "300"
  LOG_LEVEL: "info"
  MODEL_TYPE: "mini"