apiVersion: v1
kind: Service
metadata:
  name: transformer-api-service
spec:
  selector:
    app: transformer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer